package com.hydra.connect.admin
import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import okhttp3.*;import okhttp3.MediaType.Companion.toMediaTypeOrNull;import okhttp3.RequestBody.Companion.toRequestBody;import org.json.*;import java.io.IOException
class MainActivity:AppCompatActivity(){
 val http=OkHttpClient();var token="";lateinit var root:LinearLayout;val bg=Color.rgb(5,8,17);val card=Color.rgb(16,20,34);val purple=Color.rgb(139,124,255);val teal=Color.rgb(29,211,190);val muted=Color.rgb(170,176,196)
 override fun onCreate(b:Bundle?){super.onCreate(b);token=getSharedPreferences("a",0).getString("t","")?:"";if(token=="")login() else dashboard()}
 fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();fun shape(c:Int)=GradientDrawable().apply{setColor(c);cornerRadius=dp(16).toFloat()}
 fun t(s:String,z:Float=15f,c:Int=Color.WHITE,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(c);typeface=if(b)Typeface.DEFAULT_BOLD else Typeface.DEFAULT}
 fun screen(title:String,back:Boolean=true){val sv=ScrollView(this).apply{setBackgroundColor(bg)};root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(20),dp(18),dp(30))};sv.addView(root);setContentView(sv);val h=LinearLayout(this);if(back)h.addView(btn("‹").apply{setOnClickListener{dashboard()}},LinearLayout.LayoutParams(dp(52),dp(52)));h.addView(t(title,25f,Color.WHITE,true));root.addView(h);gap()}
 fun gap(v:Int=12){root.addView(Space(this),LinearLayout.LayoutParams(1,dp(v)))};fun btn(s:String)=Button(this).apply{text=s;isAllCaps=false;setTextColor(Color.WHITE);background=shape(purple)}
 fun input(h:String,secret:Boolean=false)=EditText(this).apply{hint=h;setTextColor(Color.WHITE);setHintTextColor(muted);background=shape(card);setPadding(dp(14),dp(12),dp(14),dp(12));if(secret)inputType=129}
 fun box()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(15),dp(15),dp(15),dp(15));background=shape(card)}
 fun login(){screen("HYDRA CONNECT ADMIN",false);root.addView(t("Seller control centre",14f,purple,true));gap(20);val u=input("Admin username");val p=input("Password",true);root.addView(u);gap();root.addView(p);gap();root.addView(btn("Sign in").apply{setOnClickListener{api(JSONObject().put("action","login").put("username",u.text.toString()).put("password",p.text.toString()),false){j->if(j.optBoolean("ok")){token=j.optString("token");getSharedPreferences("a",0).edit().putString("t",token).apply();dashboard()}else toast("Login failed")}}})}
 fun dashboard(){api(JSONObject().put("action","dashboard")){j->if(!j.optBoolean("ok")){logout();return@api};screen("HYDRA CONNECT ADMIN",false);val hero=box();hero.gravity=Gravity.CENTER;hero.background=GradientDrawable(GradientDrawable.Orientation.TL_BR,intArrayOf(Color.rgb(25,24,55),Color.rgb(7,32,39),Color.rgb(5,8,17))).apply{cornerRadius=dp(24).toFloat()};hero.addView(t("HYDRA CONNECT",25f,Color.WHITE,true).apply{gravity=Gravity.CENTER});hero.addView(t("ADMIN CONTROL CENTRE",11f,teal,true).apply{gravity=Gravity.CENTER;letterSpacing=.14f});hero.addView(t("Signed in as "+j.optString("admin"),12f,muted).apply{gravity=Gravity.CENTER});root.addView(hero);gap();val service=box();service.addView(t("SERVICE STATUS",10f,teal,true));service.addView(t(j.optString("service_status"),18f,Color.WHITE,true));service.setOnClickListener{status(j.optString("service_status"))};root.addView(service);gap();root.addView(t("QUICK ACCESS",11f,muted,true));gap(8);val grid=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val items=arrayOf(arrayOf("Messages","Customer conversations"),arrayOf("Renewals",j.optInt("renewals").toString()+" pending"),arrayOf("Support Reports",j.optInt("tickets").toString()+" open"),arrayOf("Customers","Account details"),arrayOf("Service Status","Update instantly"),arrayOf("Sign out","Securely leave admin"));for(i in items.indices step 2){val row=LinearLayout(this);for(k in i..minOf(i+1,items.lastIndex)){val idx=k;val x=box();x.minimumHeight=dp(112);x.gravity=Gravity.CENTER_VERTICAL;x.addView(t(items[k][0],16f,Color.WHITE,true));x.addView(t(items[k][1],12f,if(k==1||k==2)purple else muted));x.setOnClickListener{when(idx){0->conversations();1->renewals();2->tickets();3->customers();4->status(j.optString("service_status"));5->logout()}};row.addView(x,LinearLayout.LayoutParams(0,-2,1f).apply{if(k==i)marginEnd=dp(6) else marginStart=dp(6)})};grid.addView(row);grid.addView(Space(this),LinearLayout.LayoutParams(1,dp(12)))};root.addView(grid)}}
 fun menu(a:String,b:String,go:()->Unit){val x=box();x.addView(t(a,17f,Color.WHITE,true));x.addView(t(b,12f,muted));x.setOnClickListener{go()};root.addView(x);gap()}
 fun renewals(){api(JSONObject().put("action","renewals")){j->screen("Renewals");val a=j.optJSONArray("renewals")?:JSONArray();for(i in 0 until a.length()){val r=a.getJSONObject(i);val x=box();x.addView(t(r.optString("display_name",r.optString("username")),17f,Color.WHITE,true));x.addView(t("Expiry: "+r.optString("expiry_at","Unknown"),12f,muted));x.addView(t("Status: "+r.optString("status").uppercase(),12f,if(r.optString("status")=="completed")teal else purple,true));val sp=Spinner(this);val v=arrayOf("pending","seen","processing","completed");sp.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,v);sp.setSelection(v.indexOf(r.optString("status")).coerceAtLeast(0));x.addView(sp);x.addView(btn("Update status").apply{setOnClickListener{api(JSONObject().put("action","renewal_update").put("id",r.optInt("id")).put("status",sp.selectedItem.toString())){renewals()}}});root.addView(x);gap()}}}
 fun tickets(){api(JSONObject().put("action","tickets")){j->screen("Support Reports");val a=j.optJSONArray("tickets")?:JSONArray();for(i in 0 until a.length()){val r=a.getJSONObject(i);val x=box();x.addView(t(r.optString("display_name",r.optString("username")),16f,Color.WHITE,true));x.addView(t(r.optString("subject"),15f,purple,true));x.addView(t(r.optString("body"),14f));x.addView(t(r.optString("category")+" • "+r.optString("status"),11f,muted));for(s in arrayOf("open","processing","closed"))x.addView(btn(s).apply{setOnClickListener{api(JSONObject().put("action","ticket_update").put("id",r.optInt("id")).put("status",s)){tickets()}}});root.addView(x);gap()}}}
 fun conversations(){api(JSONObject().put("action","conversations")){j->screen("Messages");val a=j.optJSONArray("conversations")?:JSONArray();for(i in 0 until a.length()){val r=a.getJSONObject(i);menu(r.optString("display_name",r.optString("username")),"Last: "+r.optString("last_message")){messages(r.optInt("id"),r.optString("display_name",r.optString("username")))}}}}
 fun messages(id:Int,name:String){api(JSONObject().put("action","messages").put("customer_id",id)){j->screen(name);val a=j.optJSONArray("messages")?:JSONArray();for(i in 0 until a.length()){val m=a.getJSONObject(i);val seller=m.optString("sender")!="customer";val x=box();x.background=shape(if(seller)Color.rgb(48,38,90) else Color.rgb(12,67,65));x.addView(t(if(seller)"SELLER" else "CUSTOMER",10f,if(seller)purple else teal,true));x.addView(t(m.optString("body")));x.addView(t(m.optString("created_at"),10f,muted));root.addView(x);gap(7)};val e=input("Reply to customer…");root.addView(e);gap();root.addView(btn("Send reply").apply{setOnClickListener{if(e.text.isNotBlank())api(JSONObject().put("action","send_message").put("customer_id",id).put("body",e.text.toString())){messages(id,name)}}})}}
 fun customers(){api(JSONObject().put("action","customers")){j->screen("Customers");val a=j.optJSONArray("customers")?:JSONArray();for(i in 0 until a.length()){val r=a.getJSONObject(i);val x=box();x.addView(t(r.optString("display_name",r.optString("username")),16f,Color.WHITE,true));x.addView(t("Username: "+r.optString("username"),12f,muted));x.addView(t("Expiry: "+r.optString("expiry_at","Unknown")+" • "+r.optString("status"),12f,muted));root.addView(x);gap()}}}
 fun status(cur:String){screen("Service Status");root.addView(t("Current: "+cur,18f,teal,true));gap();for(s in arrayOf("All systems operational","Service issues reported","Maintenance in progress")){root.addView(btn(s).apply{setOnClickListener{api(JSONObject().put("action","status_update").put("service_status",s)){dashboard()}}});gap()};val e=input("Custom status");root.addView(e);gap();root.addView(btn("Publish custom status").apply{setOnClickListener{if(e.text.isNotBlank())api(JSONObject().put("action","status_update").put("service_status",e.text.toString())){dashboard()}}})}
 fun api(j:JSONObject,auth:Boolean=true,done:(JSONObject)->Unit){val rb=j.toString().toRequestBody("application/json".toMediaTypeOrNull());val r=Request.Builder().url(Config.API_URL).post(rb);if(auth&&token!="")r.header("Authorization","Bearer "+token);http.newCall(r.build()).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException){runOnUiThread{toast("Unable to connect")}};override fun onResponse(c:Call,rsp:Response){val raw=rsp.body?.string()?:"{}";val x=try{JSONObject(raw)}catch(e:Exception){JSONObject()};runOnUiThread{done(x)}}})}
 fun logout(){getSharedPreferences("a",0).edit().clear().apply();token="";login()};fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
}